// lib/products.js
// =============================================
// CÓMO ACTUALIZAR TUS PRODUCTOS:
// 1. Reemplaza "image" con la URL real de la imagen
// 2. Reemplaza "price" con el precio real en centavos USD (ej: $19.99 = 1999)
// 3. Actualiza "description" con la descripción real
// =============================================

export const products = [

  // ── LUBRICANTES ──────────────────────────────────────────────
  {
    id: "lub-001",
    name: "Lubricante Gelx Neutro 100ml",
    description: "Lubricante íntimo neutro de base acuosa, ultra suave. Sin fragancia ni sabor. Compatible con preservativos.",
    price: 19000,
    category: "Lubricantes",
    image: "https://badrabbit.com.co/cdn/shop/files/WhatsAppImage2024-08-15at17.33.29.jpg?v=1723761334",
    badge: "Popular",
    inStock: true,
  },
  {
    id: "lub-002",
    name: "Lubricante Íntimo Anal 20ml",
    description: "Fórmula especial para uso anal. Extra suave y deslizante. Máximo confort y seguridad.",
    price: 24000,
    category: "Lubricantes",
    image: "https://disfrutatesex.com/cdn/shop/files/P226.B.png?v=1741114975&width=823",
    badge: null,
    inStock: true,
  },
  {
    id: "lub-003",
    name: "Lubricante Natural x 500ml",
    description: "Presentación familiar de 500ml con ingredientes naturales. Compatible con preservativos.",
    price: 39000,
    category: "Lubricantes",
    image: "https://senintimo.co/cdn/shop/files/952b4526141a568dd46227addb558b7847a3cbbc.png?v=1703257700&width=1346",
    badge: "Mejor Valor",
    inStock: true,
  },
  {
    id: "lub-004",
    name: "Lubricante Piel Sensible Elixir 500ml",
    description: "Especialmente formulado para pieles sensibles. Sin parabenos ni colorantes artificiales.",
    price: 49000,
    category: "Lubricantes",
    image: "https://glowzonav.com/cdn/shop/files/Diseno-sin-titulo-20.jpg?v=1757358584&width=1100",
    badge: null,
    inStock: true,
  },
  {
    id: "lub-005",
    name: "Lubricante Cum Sensitive 250ml",
    description: "Lubricante premium de textura única. Fórmula sensitiva para mayor placer.",
    price: 69000,
    category: "Lubricantes",
    image: "https://senintimo.co/cdn/shop/files/ecca0f8ad4174.png?v=1703258032&width=1346",
    badge: "Nuevo",
    inStock: true,
  },
  {
    id: "lub-006",
    name: "Lubricante Cremoso Elixir 250ml",
    description: "Textura cremosa de larga duración. Hidrata y lubrica al mismo tiempo.",
    price: 39000,
    category: "Lubricantes",
    image: "https://locatelcolombia.vtexassets.com/arquivos/ids/395697-1200-1200?v=638801595279670000&width=1200&height=1200&aspect=true",
    badge: null,
    inStock: true,
  },
  {
    id: "lub-007",
    name: "Lubricante Saborizado Sandía 30ml",
    description: "Delicioso sabor a sandía. Perfecto para juegos íntimos. Base acuosa, comestible.",
    price: 29000,
    category: "Lubricantes",
    image: "https://locatelcolombia.vtexassets.com/arquivos/ids/395686-1600-1600?v=638801595260200000&width=1600&height=1600&aspect=true",
    badge: null,
    inStock: true,
  },
  {
    id: "lub-008",
    name: "Lubricante Saborizado Fresa 30ml",
    description: "Irresistible sabor a fresa bombón. Ideal para estimulación oral. Sin azúcar.",
    price: 29000,
    category: "Lubricantes",
    image: "https://locatelcolombia.vtexassets.com/arquivos/ids/395700-1200-1200?v=638801595289570000&width=1200&height=1200&aspect=true",
    badge: null,
    inStock: true,
  },

  // ── LENCERÍA ─────────────────────────────────────────────────
  {
    id: "len-001",
    name: "Sweet Apple",
    description: "Conjunto de lencería seductor con detalles de encaje. Tallas S-XL. Varios colores.",
    price: 89000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I691.jpg?v=1764437854",
    badge: "Favorita",
    inStock: true,
  },
  {
    id: "len-002",
    name: "Sea Beauty",
    description: "Conjunto inspirado en el mar, tonos azules y verdes. Encaje fino y tiras ajustables.",
    price: 99000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I942.jpg?v=1764437943",
    badge: null,
    inStock: true,
  },
  {
    id: "len-003",
    name: "Office Lover",
    description: "Elegante conjunto con aire de oficina. Negro clásico con detalles sutiles y atrevidos.",
    price: 45000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I444.png?v=1761087717",
    badge: null,
    inStock: true,
  },
  {
    id: "len-004",
    name: "Disfraz Noelita Lerot",
    description: "Disfraz seductor navideño con accesorios incluidos. Tallas S-XL.",
    price: 59000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I623.jpg?v=1762815781",
    badge: "Nuevo",
    inStock: true,
  },
  {
    id: "len-005",
    name: "Set Intense Negro",
    description: "Conjunto intensamente seductor en negro. Encaje y transparencias estratégicas.",
    price: 79000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I596.jpg?v=1771355751",
    badge: "Hot 🔥",
    inStock: true,
  },
  {
    id: "len-006",
    name: "Set Electra Azul-Verde",
    description: "Conjunto vibrante en tonos azul y verde. Diseño único con detalles metálicos.",
    price: 99000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I072.png?v=1771355480",
    badge: null,
    inStock: true,
  },
  {
    id: "len-007",
    name: "Set Divine",
    description: "Lencería divina con encaje de alta calidad. Siéntete una diosa.",
    price: 85000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/SETDIVINE.jpg?v=1753973506",
    badge: "Premium",
    inStock: true,
  },
  {
    id: "len-008",
    name: "Set Wild",
    description: "Para la mujer salvaje. Estampados animales y cortes atrevidos.",
    price: 99000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/SETWILD.jpg?v=1751570195",
    badge: null,
    inStock: true,
  },
  {
    id: "len-009",
    name: "Set Lyra",
    description: "Inspirado en las constelaciones. Detalles brillantes sobre tejido transparente.",
    price: 99000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/I269_1_b2e7e077-c7e4-4ae9-a9ab-e2c91f0bb70d.jpg?v=1741401826",
    badge: null,
    inStock: true,
  },
  {
    id: "len-010",
    name: "Vestido de Malla Encanto Nocturno",
    description: "Vestido de malla transparente con diseño floral. Elegante y provocador.",
    price: 89000,
    category: "Lencería",
    image: "https://sexsymbol.com.co/cdn/shop/files/m092.png?v=1771356456",
    badge: "Exclusivo",
    inStock: true,
  },

  // ── JUEGOS SEXUALES ───────────────────────────────────────────
  {
    id: "jue-001",
    name: "Jenga Picante",
    description: "El clásico Jenga con retos y preguntas íntimas. Para parejas aventureras.",
    price: 39000,
    category: "Juegos Sexuales",
    image: "https://media.falabella.com/falabellaCO/144630726_04/w=1500,h=1500,fit=cover",
    badge: "Bestseller",
    inStock: true,
  },
  {
    id: "jue-002",
    name: "Dados Sexo Oral",
    description: "Set de dados con posiciones y acciones para sexo oral. Sorprende a tu pareja.",
    price: 14000,
    category: "Juegos Sexuales",
    image: "https://sintabuesoficial.com/cdn/shop/files/wanna-dados-sexo-oral_4.jpg?v=1767680085&width=1200",
    badge: null,
    inStock: true,
  },
  {
    id: "jue-003",
    name: "Toma Todo Party Poses",
    description: "Juego de poses para parejas. Tarjetas con posiciones y retos divertidos.",
    price: 49000,
    category: "Juegos Sexuales",
    image: "https://exoticshopcr.com/cdn/shop/files/C77E69F9-0462-4D39-BAAD-1D49FB7654A3.png?v=1748307128&width=990",
    badge: "Nuevo",
    inStock: true,
  },
  {
    id: "jue-004",
    name: "Dados Eróticos x2",
    description: "Par de dados eróticos con posiciones y acciones. Perfecto para noches de pasión.",
    price: 49000,
    category: "Juegos Sexuales",
    image: "https://static.wixstatic.com/media/68eca0_4dadf335a1b345ddab9f14aa6c010afc~mv2.jpg/v1/fit/w_636,h_669,q_90,enc_avif,quality_auto/68eca0_4dadf335a1b345ddab9f14aa6c010afc~mv2.jpg",
    badge: null,
    inStock: true,
  },
  {
    id: "jue-005",
    name: "Juego Fantasía",
    description: "Kit completo de juego de roles y fantasías. Incluye tarjetas, dados y accesorios.",
    price: 35000,
    category: "Juegos Sexuales",
    image: "https://badrabbit.com.co/cdn/shop/products/JJ0005.png?v=1622219536",
    badge: "Popular",
    inStock: true,
  },
  {
    id: "jue-006",
    name: "Kamasutra Juego de Mesa",
    description: "Juego de mesa erótico con posiciones del Kamasutra. Para parejas que quieren explorar.",
    price: 35000,
    category: "Juegos Sexuales",
    image: "https://sexosentido.co/cdn/shop/products/kama.jpg?v=1694623052",
    badge: "Hot 🔥",
    inStock: true,
  },

  // ── VIBRADORES Y CONSOLADORES ─────────────────────────────────
  {
    id: "vib-001",
    name: "Legendary King Realistic Dildo 11\"",
    description: "Dildo realista de gran tamaño, 11 pulgadas. Material premium, base con ventosa.",
    price: 69000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/products/A229_1.jpg?v=1642889840",
    badge: "Más Vendido",
    inStock: true,
  },
  {
    id: "vib-002",
    name: "Consolador Richard",
    description: "Diseño realista premium. Textura suave al tacto, flexible y resistente.",
    price: 79000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/files/A227_4.jpg?v=1689252032",
    badge: null,
    inStock: true,
  },
  {
    id: "vib-003",
    name: "Realistic Dildo 6\" Thin Dong",
    description: "Dildo realista delgado de 6 pulgadas. Ideal para principiantes. Ventosa incluida.",
    price: 49000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/files/A065_1.jpg?v=1748404481",
    badge: "Para Principiantes",
    inStock: true,
  },
  {
    id: "vib-004",
    name: "Vibrador Lennon",
    description: "Vibrador con múltiples velocidades y patrones. Recargable por USB. Silencioso.",
    price: 149000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/files/B385_1.jpg?v=1689252743",
    badge: "Nuevo",
    inStock: true,
  },
  {
    id: "vib-005",
    name: "Dildo Alex 27cm",
    description: "Dildo realista de 27cm. Material tipo piel sensible de altísima calidad.",
    price: 109000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/products/A303_6.jpg?v=1679780298",
    badge: "Premium",
    inStock: true,
  },
  {
    id: "vib-006",
    name: "Vagina y Boca Abigail",
    description: "Masturbador masculino doble entrada. Textura interior ultra-realista.",
    price: 99000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/files/L134_1_d834c66b-5dda-45b8-baba-614b95453c60.jpg?v=1693941480",
    badge: "Para Él",
    inStock: true,
  },
  {
    id: "vib-007",
    name: "Vibrador Estimulador Recargable",
    description: "Doble estimulación con 10 modos de vibración. 100% impermeable y recargable.",
    price: 75000,
    category: "Vibradores y Consoladores",
    image: "https://m.media-amazon.com/images/I/61cMQ3IPeyL._AC_UF1000,1000_QL80_.jpg",
    badge: "Top Ventas",
    inStock: true,
  },
  {
    id: "vib-008",
    name: "Vibrador Punto G",
    description: "Diseñado específicamente para estimulación del punto G. 12 intensidades.",
    price: 89000,
    category: "Vibradores y Consoladores",
    image: "https://m.media-amazon.com/images/I/71-bL4uUFuL._AC_UF1000,1000_QL80_.jpg",
    badge: null,
    inStock: true,
  },
  {
    id: "vib-009",
    name: "Consolador Glicerina",
    description: "Consolador de glicerina suave y flexible. Se adapta a la temperatura del cuerpo.",
    price: 66000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/products/A289_1.jpg?v=1668198090",
    badge: null,
    inStock: true,
  },
  {
    id: "vib-010",
    name: "Arnés Realista Lemar",
    description: "Arnés con dildo realista incluido. Completamente ajustable. Todos los cuerpos.",
    price: 110000,
    category: "Vibradores y Consoladores",
    image: "https://sexsymbol.com.co/cdn/shop/files/a043.png?v=1760552576",
    badge: "Exclusivo",
    inStock: true,
  },
  {
    id: "vib-011",
    name: "Masturbador Genesys Net",
    description: "Masturbador premium con textura de red interior. Incluye lubricante Sen Íntimo.",
    price: 89000,
    category: "Vibradores y Consoladores",
    image: "https://tiendacereza.com/cdn/shop/files/63a203598c8dcf_897x897.png?v=1772574220",
    badge: "Incluye Lubricante",
    inStock: true,
  },
  {
    id: "vib-012",
    name: "Masturbador Palm Stroker No.1",
    description: "Masturbador compacto y discreto color azul. Textura interior suave y estimulante.",
    price: 59000,
    category: "Vibradores y Consoladores",
    image: "https://tiendacereza.com/cdn/shop/files/9dc1dcadbffbf38aae3961c280e508de32f918d5_897x897.png?v=1754437457",
    badge: null,
    inStock: true,
  },
];

export const categories = ["Lubricantes", "Lencería", "Juegos Sexuales", "Vibradores y Consoladores"];

export function getProductById(id) {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category) {
  return products.filter(p => p.category === category);
}

export function formatPrice(cents) {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
  }).format(cents);
}
